[project]
name = "spherical-scikit-learn"
version = "0.1.2"
description = "A toolkit for spherical k-means and von Mises-Fisher mixture models"
dependencies = [
    "scikit-learn>=1.4.1.post1",
    "numpy>=1.20.0",
    "scipy>=0.11.0",
    "threadpoolctl>=2.2.0",
]

[project.urls]
Documentation = "https://lijiaqi.github.io/spherical-scikit-learn/"
Repository = "https://github.com/lijiaqi/spherical-scikit-learn.git"

[project.optional-dependencies]
test = ["pytest", "matplotlib"]
dev = ["pytest", "matplotlib", "build", "setuptools>=42", "Cython>=3.0"]

[build-system]
requires = [
    "setuptools>=61",
    "wheel",
    "Cython>=3.0",
    "scikit-learn>=1.4.1.post1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"spsklearn.cluster" = ["*.pyx", "*.pxd"]

[tool.setuptools]
packages = [
    "spsklearn",
    "spsklearn.cluster",
    "spsklearn.mixture",
    "spsklearn.utils",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
